name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.4'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Vault-Cracker'
          options: --onefile, --name "Vault-Cracker", --windowed
