name: Package exe with PyInstaller - Windows

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
      - uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.4'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Vault-Cracker.exe'
          options: --onefile, --name "Vault-Cracker.exe", --windowed
      - uses: xresloader/upload-to-github-release@v1
        with:
          file: "Vault-Cracker.exe"
